FROM ubuntu:24.04
MAINTAINER tim@cyface.com

ENV APT_KEY_DONT_WARN_ON_DANGEROUS_USAGE=1
RUN echo 'debconf debconf/frontend select Noninteractive' | debconf-set-selections
RUN apt-get update -y
RUN apt-get install apt-utils curl wget gnupg -y

### Add SaltStack repository and GPG key
# Ensure keyrings dir exists
RUN mkdir -p /etc/apt/keyrings
# Download public key
RUN curl -fsSL https://packages.broadcom.com/artifactory/api/security/keypair/SaltProjectKey/public | tee /etc/apt/keyrings/salt-archive-keyring.pgp
# Create apt repo target configuration
RUN curl -fsSL https://github.com/saltstack/salt-install-guide/releases/latest/download/salt.sources | tee /etc/apt/sources.list.d/salt.sources

# Pin SaltStack packages to 3006.* version
RUN printf 'Package: salt-*\nPin: version 3006.*\nPin-Priority: 1001\n' | tee /etc/apt/preferences.d/salt-pin-1001

# Update package list and install SaltStack packages
RUN apt-get update -y
RUN apt-get install salt-minion salt-ssh -y
RUN apt-get install dnsutils tree vim -y
RUN apt-get clean all

# Configure Salt Master
RUN sed -i "s|#master: salt|master: salt-master|g" /etc/salt/minion

# Configure Shell Prompt
RUN echo "PS1='\[\033[01;32m\]\u@salt-minion\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]\$ '" >> /root/.bashrc

# Add a script to set grains
COPY minion-entrypoint.sh /minion-entrypoint.sh
RUN chmod +x minion-entrypoint.sh

# Add supervisord configuration
RUN apt-get install supervisor -y
RUN apt-get clean all
COPY minion-supervisord.conf /etc/supervisor/conf.d/supervisord.conf

# Start supervisord
ENTRYPOINT ["/usr/bin/supervisord"]
