services:
  salt-master:
    build:
      context: .
      dockerfile: Dockerfile.master
    image: salt-master
  salt-minion:
    build:
      context: .
      dockerfile: Dockerfile.minion
    image: salt-minion
    depends_on:
      - salt-master
    deploy:
      replicas: 0
    environment:
      - ROLES=ninja turtle
      - ENV=staging
